language: node_js
node_js:
  - "node"
install:
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iotaeco/iota-pico-core.git iotaeco/iota-pico-core
  - cd iotaeco/iota-pico-core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iotaeco/iota-pico-api.git iotaeco/iota-pico-api
  - cd iotaeco/iota-pico-api
  - npm link @iota-pico/core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iotaeco/iota-pico-data.git iotaeco/iota-pico-data
  - cd iotaeco/iota-pico-data
  - npm link @iota-pico/core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iotaeco/iota-pico-crypto.git iotaeco/iota-pico-crypto
  - cd iotaeco/iota-pico-crypto
  - npm link @iota-pico/core @iota-pico/data
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iotaeco/iota-pico-pow-js.git iotaeco/iota-pico-pow-js
  - cd iotaeco/iota-pico-pow-js
  - npm link @iota-pico/core @iota-pico/data @iota-pico/crypto
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iotaeco/iota-pico-pal-nodejs.git iotaeco/iota-pico-pal-nodejs
  - cd iotaeco/iota-pico-pal-nodejs
  - npm link @iota-pico/core
  - npm link
  - cd ../iota-pico-tutorials
script:
  - cd getNodeInfo
  - npm link @iota-pico/core @iota-pico/api @iota-pico/pal-nodejs
  - node getNodeInfo
  - cd ../proofOfWork
  - npm link @iota-pico/core @iota-pico/data @iota-pico/crypto @iota-pico/pow-js
  - node proofOfWork
