language: node_js
node_js:
  - "8"
install:
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/core.git core
  - cd https://github.com/iota-pico/core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/api.git api
  - cd https://github.com/iota-pico/api
  - npm link @iota-pico/core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/data.git data
  - cd https://github.com/iota-pico/data
  - npm link @iota-pico/core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/crypto.git crypto
  - cd https://github.com/iota-pico/crypto
  - npm link @iota-pico/core @iota-pico/data
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/business.git business
  - cd https://github.com/iota-pico/business
  - npm link @iota-pico/core @iota-pico/data @iota-pico/crypto @iota-pico/api
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/pow-js.git pow-js
  - cd https://github.com/iota-pico/pow-js
  - npm link @iota-pico/core @iota-pico/data @iota-pico/crypto
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/pow-box.git pow-box
  - cd https://github.com/iota-pico/pow-box
  - npm link @iota-pico/core @iota-pico/data @iota-pico/crypto
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/pow-wasm.git pow-wasm
  - cd https://github.com/iota-pico/pow-wasm
  - npm link @iota-pico/core @iota-pico/data @iota-pico/crypto
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/pow-webgl.git pow-webgl
  - cd https://github.com/iota-pico/pow-webgl
  - npm link @iota-pico/core @iota-pico/data @iota-pico/crypto
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/pow-nodejs.git pow-nodejs
  - cd https://github.com/iota-pico/pow-nodejs
  - npm link @iota-pico/core @iota-pico/data @iota-pico/crypto
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/pal-browser.git pal-browser
  - cd https://github.com/iota-pico/pal-browser
  - npm link @iota-pico/core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/pal-nodejs.git pal-nodejs
  - cd https://github.com/iota-pico/pal-nodejs
  - npm link @iota-pico/core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/lib-browser.git lib-browser
  - cd https://github.com/iota-pico/lib-browser
  - npm link @iota-pico/core @iota-pico/data @iota-pico/api @iota-pico/crypto @iota-pico/business @iota-pico/pal-browser @iota-pico/pow-js @iota-pico/pow-box @iota-pico/pow-wasm @iota-pico/pow-webgl
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/lib-nodejs.git lib-nodejs
  - cd https://github.com/iota-pico/lib-nodejs
  - npm link @iota-pico/core @iota-pico/data @iota-pico/api @iota-pico/crypto @iota-pico/business @iota-pico/pal-nodejs @iota-pico/pow-js @iota-pico/pow-box @iota-pico/pow-wasm @iota-pico/pow-nodejs  
  - npm link
  - cd ../tutorials
script:
  - cd using-library/node-js/getNodeInfoNodeJS
  - npm link @iota-pico/lib-nodejs || travis_terminate 1
  - npm install || travis_terminate 1
  - npm run build || travis_terminate 1
  - node getNodeInfo.js || travis_terminate 1
  - cd ../../../using-modules/node-js/getNodeInfoNodeJS
  - npm link @iota-pico/core @iota-pico/api @iota-pico/pal-nodejs || travis_terminate 1
  - npm install || travis_terminate 1
  - npm run build || travis_terminate 1
  - node getNodeInfo.js || travis_terminate 1
  - cd ../../../using-modules/node-js/proofOfWorkNodeJS
  - npm link @iota-pico/core @iota-pico/api @iota-pico/data @iota-pico/crypto @iota-pico/pal-nodejs @iota-pico/pow-nodejs @iota-pico/pow-wasm @iota-pico/pow-js || travis_terminate 1
  - npm install || travis_terminate 1
  - npm run build || travis_terminate 1
  - node proofOfWork.js || travis_terminate 1
